encoding: "utf-8"
locale: "ja-JP"
timezone: "Asia/Tokyo"
baseurl: /christ/

theme: jekyll-theme-midnight
layout: default

title: Nick on github.io
description: 福音のためなら、わたしはどんなことでもします。それは、わたしが福音に共にあずかる者となるためです。 (1co9:23)
url: https://astrorobot110.github.io/christ/
